version: '3'
services:
  app:
    build: .
    container_name: todo_app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todoapp
      - JWT_SECRET=just a secret
      - NODE_ENV=development
      - PORT=5003
    ports:
      - "5003:5003"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules  # Critical fix - prevents permission conflicts
    user: "1000:1000"  # Better than root for security

  db:
    image: postgres:13-alpine
    container_name: postgres-db
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: